import { useMemo, useState } from "react";
import { CheckCircle2, Download, Loader2, Upload } from "lucide-react";
import { toast } from "sonner";
import { LEMTEL_ONBOARDING_ENABLED, LemtelError, portalApi, type LemtelLocale, type ProvisionedUser } from "./lemtelHostedApi";
import type { Lang, LemtelDict } from "./lemtelI18n";
import { Field, Panel } from "./LemtelUi";
import { LemtelEmailPreview, type DownloadLinks } from "./LemtelEmailPreview";
import { csvTemplate, LEMTEL_ROLES, parseLemtelCsv, resultsCsv, type ParsedRow } from "./lemtelCsv";

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;
const SLUG_RE = /^[a-z0-9](?:[a-z0-9-]{1,46}[a-z0-9])$/;
const slugify = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48);
const errorText = (t: LemtelDict, error: unknown) => t.errors[error instanceof LemtelError ? error.key : "generic"];

function download(name: string, content: string) {
  const url = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" }));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url);
}

export function NewOrgDialog({ open, onClose, t, links, support, existingSlugs, onCreated }: { open: boolean; onClose: () => void; t: LemtelDict; links: DownloadLinks; support?: string; existingSlugs: string[]; onCreated: () => void }) {
  const [step, setStep] = useState<1 | 2>(1);
  const [form, setForm] = useState({ name: "", slug: "", locale: "fr" as Lang, ownerName: "", ownerEmail: "" });
  const [slugTouched, setSlugTouched] = useState(false); const [touched, setTouched] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const set = (key: keyof typeof form, value: string) => setForm((previous) => ({ ...previous, [key]: value, ...(key === "name" && !slugTouched ? { slug: slugify(value) } : {}) }));
  const errors = { name: !form.name.trim() ? t.errors.invalid_input : "", slug: !SLUG_RE.test(form.slug) ? t.slugHint : existingSlugs.includes(form.slug) ? t.errors.conflict : "", ownerName: !form.ownerName.trim() ? t.errors.invalid_input : "", ownerEmail: !EMAIL_RE.test(form.ownerEmail.trim()) ? t.errors.invalid_input : "" };
  const valid = Object.values(errors).every((value) => !value);
  const close = () => { setStep(1); setError(null); setTouched(false); onClose(); };
  const submit = async () => {
    setBusy(true); setError(null);
    try {
      await portalApi.createOrganization({ displayName: form.name.trim(), slug: form.slug, defaultLocale: form.locale, owner: { email: form.ownerEmail.trim().toLowerCase(), displayName: form.ownerName.trim(), locale: form.locale } });
      toast.success(t.orgCreated); setForm({ name: "", slug: "", locale: "fr", ownerName: "", ownerEmail: "" }); setSlugTouched(false); onCreated(); close();
    } catch (cause) { setError(errorText(t, cause)); } finally { setBusy(false); }
  };
  return <Panel open={open} onClose={close} title={t.newOrg} wide footer={step === 1 ? <><button className="lt-btn lt-btn-ghost" onClick={close}>{t.cancel}</button><button className="lt-btn lt-btn-gold" onClick={() => { setTouched(true); if (valid) setStep(2); }}>{t.next}</button></> : <><button className="lt-btn lt-btn-ghost" onClick={() => setStep(1)}>{t.back}</button><button className="lt-btn lt-btn-gold" disabled={busy || !LEMTEL_ONBOARDING_ENABLED} onClick={submit}>{busy && <Loader2 className="w-4 h-4 animate-spin" />}{t.create}</button></>}>
    {step === 1 ? <div className="grid md:grid-cols-2 gap-4"><Field label={t.orgName} error={touched ? errors.name : undefined}>{(id) => <input id={id} className="lt-input" value={form.name} onChange={(event) => set("name", event.target.value)} />}</Field><Field label={t.slug} error={touched || slugTouched ? errors.slug || undefined : undefined} hint={t.slugHint}>{(id, describedBy) => <input id={id} aria-describedby={describedBy} className="lt-input font-mono" value={form.slug} onChange={(event) => { setSlugTouched(true); set("slug", event.target.value.toLowerCase()); }} />}</Field><Field label={t.defaultLang}>{(id) => <select id={id} className="lt-input" value={form.locale} onChange={(event) => set("locale", event.target.value)}><option value="fr">{t.french}</option><option value="en">{t.english}</option></select>}</Field><div /><Field label={t.adminName} error={touched ? errors.ownerName : undefined}>{(id) => <input id={id} className="lt-input" value={form.ownerName} onChange={(event) => set("ownerName", event.target.value)} />}</Field><Field label={t.adminEmail} error={touched ? errors.ownerEmail : undefined}>{(id) => <input id={id} type="email" className="lt-input" value={form.ownerEmail} onChange={(event) => set("ownerEmail", event.target.value)} />}</Field></div> : <div className="grid md:grid-cols-[1fr_1.1fr] gap-6"><section aria-labelledby="lt-security" className="space-y-3"><h3 id="lt-security" className="font-semibold">{t.securityTitle}</h3><ul className="space-y-2">{t.securityItems.map((item) => <li key={item} className="flex gap-2 text-sm"><CheckCircle2 className="w-4 h-4 mt-0.5 shrink-0" style={{ color: "hsl(var(--lt-green))" }} />{item}</li>)}</ul>{error && <p className="lt-error" role="alert">{error}</p>}{!LEMTEL_ONBOARDING_ENABLED && <p className="lt-notice px-3 py-2 text-xs">{t.readonlyBody}</p>}</section><section aria-label={t.previewEmail}><h3 className="font-semibold mb-2">{t.previewEmail} · {form.locale.toUpperCase()}</h3><LemtelEmailPreview lang={form.locale} name={form.ownerName} email={form.ownerEmail} org={form.name} links={links} support={support} /></section></div>}
  </Panel>;
}

export function InviteDrawer({ open, onClose, t, orgId, defaultLocale, onDone }: { open: boolean; onClose: () => void; t: LemtelDict; orgId: string | null; defaultLocale: LemtelLocale; onDone: () => void }) {
  const blank = { first: "", last: "", email: "", locale: defaultLocale, role: "member" as const };
  const [form, setForm] = useState(blank); const [touched, setTouched] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const invalid = { first: !form.first.trim(), last: !form.last.trim(), email: !EMAIL_RE.test(form.email.trim()) };
  const submit = async () => {
    setTouched(true); if (Object.values(invalid).some(Boolean) || !orgId) return;
    setBusy(true); setError(null);
    try { await portalApi.provisionUsers(orgId, [{ email: form.email.trim().toLowerCase(), displayName: `${form.first.trim()} ${form.last.trim()}`, role: form.role, locale: form.locale }]); toast.success(t.inviteSent); setForm(blank); setTouched(false); onDone(); onClose(); } catch (cause) { setError(errorText(t, cause)); } finally { setBusy(false); }
  };
  return <Panel open={open} onClose={onClose} title={t.invitePerson} side footer={<><button className="lt-btn lt-btn-ghost" onClick={onClose}>{t.cancel}</button><button className="lt-btn lt-btn-gold" disabled={busy || !LEMTEL_ONBOARDING_ENABLED || !orgId} onClick={submit}>{busy && <Loader2 className="w-4 h-4 animate-spin" />}{t.invite}</button></>}><div className="space-y-4"><div className="grid grid-cols-2 gap-3"><Field label={t.firstName} error={touched && invalid.first ? t.errors.invalid_input : undefined}>{(id) => <input id={id} className="lt-input" value={form.first} onChange={(event) => setForm({ ...form, first: event.target.value })} />}</Field><Field label={t.lastName} error={touched && invalid.last ? t.errors.invalid_input : undefined}>{(id) => <input id={id} className="lt-input" value={form.last} onChange={(event) => setForm({ ...form, last: event.target.value })} />}</Field></div><Field label={t.email} error={touched && invalid.email ? t.errors.invalid_input : undefined}>{(id) => <input id={id} type="email" className="lt-input" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} />}</Field><div className="grid grid-cols-2 gap-3"><Field label={t.language}>{(id) => <select id={id} className="lt-input" value={form.locale} onChange={(event) => setForm({ ...form, locale: event.target.value as LemtelLocale })}><option value="fr">{t.french}</option><option value="en">{t.english}</option></select>}</Field><Field label={t.role}>{(id) => <select id={id} className="lt-input" value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value as ProvisionedUser["role"] })}>{LEMTEL_ROLES.map((role) => <option key={role} value={role}>{t.roles[role]}</option>)}</select>}</Field></div>{error && <p className="lt-error" role="alert">{error}</p>}{!LEMTEL_ONBOARDING_ENABLED && <p className="lt-notice px-3 py-2 text-xs">{t.readonlyBody}</p>}</div></Panel>;
}

type Result = { email: string; status: "sent" | "needs_attention" };
export function BulkInvite({ open, onClose, t, orgId, defaultLocale, onDone }: { open: boolean; onClose: () => void; t: LemtelDict; orgId: string | null; defaultLocale: LemtelLocale; onDone: () => void }) {
  const [rows, setRows] = useState<ParsedRow[] | null>(null); const [headerError, setHeaderError] = useState(false); const [drag, setDrag] = useState(false); const [step, setStep] = useState<"upload" | "preview" | "confirm" | "results">("upload"); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [results, setResults] = useState<Result[]>([]);
  const validRows = useMemo(() => (rows ?? []).filter((row) => !row.errors.length), [rows]);
  const counts = useMemo(() => ({ valid: validRows.filter((row) => !row.warnings.length).length, warning: validRows.filter((row) => row.warnings.length).length, invalid: (rows ?? []).length - validRows.length, fr: validRows.filter((row) => (row.data.language || defaultLocale) === "fr").length, en: validRows.filter((row) => (row.data.language || defaultLocale) === "en").length }), [rows, validRows, defaultLocale]);
  const reset = () => { setRows(null); setStep("upload"); setResults([]); setError(null); setHeaderError(false); };
  const close = () => { reset(); onClose(); };
  const read = async (file?: File) => { if (!file) return; const parsed = parseLemtelCsv(await file.text()); setHeaderError(parsed.headerError); setRows(parsed.rows); if (!parsed.headerError) setStep("preview"); };
  const submit = async () => {
    if (!orgId) return; setBusy(true); setError(null);
    try {
      const users: ProvisionedUser[] = validRows.map((row) => ({ email: row.data.email, displayName: `${row.data.first_name} ${row.data.last_name}`.trim(), role: row.data.role as ProvisionedUser["role"], locale: (row.data.language || defaultLocale) as LemtelLocale }));
      const response = await portalApi.provisionUsers(orgId, users);
      setResults(response.users.map((result) => ({ email: result.email, status: result.delivered ? "sent" : "needs_attention" }))); setStep("results"); onDone();
    } catch (cause) { setError(errorText(t, cause)); } finally { setBusy(false); }
  };
  return <Panel open={open} onClose={close} title={t.bulk} wide footer={step === "preview" ? <><button className="lt-btn lt-btn-ghost" onClick={reset}>{t.back}</button><button className="lt-btn lt-btn-gold" disabled={!validRows.length} onClick={() => setStep("confirm")}>{t.next}</button></> : step === "confirm" ? <><button className="lt-btn lt-btn-ghost" onClick={() => setStep("preview")}>{t.back}</button><button className="lt-btn lt-btn-gold" disabled={busy || !LEMTEL_ONBOARDING_ENABLED || !orgId} onClick={submit}>{busy && <Loader2 className="w-4 h-4 animate-spin" />}{t.confirmBulk(validRows.length)}</button></> : step === "results" ? <><button className="lt-btn lt-btn-ghost" onClick={() => download("lemtel-invitations-results.csv", resultsCsv(results))}><Download className="w-4 h-4" />{t.exportResults}</button><button className="lt-btn lt-btn-gold" onClick={close}>{t.done}</button></> : <button className="lt-btn lt-btn-ghost" onClick={() => download("lemtel-invitations-template.csv", csvTemplate())}><Download className="w-4 h-4" />{t.template}</button>}>
    {step === "upload" && <label data-active={drag} className="lt-dropzone flex flex-col items-center justify-center gap-3 p-12 cursor-pointer text-center" onDragOver={(event) => { event.preventDefault(); setDrag(true); }} onDragLeave={() => setDrag(false)} onDrop={(event) => { event.preventDefault(); setDrag(false); read(event.dataTransfer.files?.[0]); }}><Upload className="w-8 h-8" style={{ color: "hsl(var(--lt-cyan))" }} /><span className="font-medium">{t.drop}</span><input type="file" accept=".csv,text/csv" className="sr-only" onChange={(event) => read(event.target.files?.[0])} />{headerError && <span className="lt-error" role="alert">{t.headerError}</span>}</label>}
    {step === "preview" && rows && <div className="space-y-4"><div className="flex gap-2 flex-wrap"><span className="lt-chip lt-chip-ok">{counts.valid} {t.valid}</span><span className="lt-chip lt-chip-warn">{counts.warning} {t.warnings}</span><span className="lt-chip lt-chip-bad">{counts.invalid} {t.invalid}</span></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left lt-ink-2 text-xs uppercase"><th className="p-2">{t.line}</th><th className="p-2">{t.firstName}</th><th className="p-2">{t.lastName}</th><th className="p-2">Email</th><th className="p-2">{t.language}</th><th className="p-2">{t.role}</th><th className="p-2" /></tr></thead><tbody>{rows.map((row) => <tr key={row.line} className="border-t" style={{ borderColor: "hsl(var(--lt-border))" }}><td className="p-2 tabular-nums">{row.line}</td><td className="p-2">{row.data.first_name}</td><td className="p-2">{row.data.last_name}</td><td className="p-2 break-all">{row.data.email}</td><td className="p-2">{row.data.language || defaultLocale}</td><td className="p-2">{row.data.role}</td><td className="p-2">{[...row.errors.map((issue) => <span key={issue} className="lt-chip lt-chip-bad mr-1">{t.issues[issue]}</span>), ...row.warnings.map((issue) => <span key={issue} className="lt-chip lt-chip-warn mr-1">{t.issues[issue]}</span>)]}</td></tr>)}</tbody></table></div></div>}
    {step === "confirm" && <div className="space-y-4"><p className="text-lg font-semibold">{t.confirmBulk(validRows.length)}</p><p className="text-sm">{t.langDist} : FR {counts.fr} · EN {counts.en}</p>{error && <p className="lt-error" role="alert">{error}</p>}{!LEMTEL_ONBOARDING_ENABLED && <p className="lt-notice px-3 py-2 text-xs">{t.readonlyBody}</p>}</div>}
    {step === "results" && <div className="grid grid-cols-2 gap-3">{(["sent", "needs_attention"] as const).map((status) => <div key={status} className="lt-card p-4"><div className="lt-ink-2 text-xs">{status === "sent" ? t.sent : t.needsAttention}</div><div className="text-2xl font-semibold tabular-nums">{results.filter((result) => result.status === status).length}</div></div>)}</div>}
  </Panel>;
}
