import { useState } from "react";
import { Sparkles, RefreshCw, Activity, Clock, MessageSquare, Users, TrendingUp } from "lucide-react";
import type { OverviewInsight } from "@/lib/planipret/overviewInsights";
import imgPerformance from "@/assets/overview/insight-performance.jpg";
import imgAvailability from "@/assets/overview/insight-availability.jpg";
import imgProducts from "@/assets/commissions/insight-products.jpg";
import imgLenders from "@/assets/commissions/insight-lenders.jpg";
import imgGrowth from "@/assets/commissions/insight-growth.jpg";

const ART: Record<string, { img: string; accent: string; Icon: any }> = {
  performance: { img: imgPerformance, accent: "#2E9BDC", Icon: Activity },
  availability: { img: imgAvailability, accent: "#E8A33C", Icon: Clock },
  communication: { img: imgProducts, accent: "#9B7FE8", Icon: MessageSquare },
  clients: { img: imgLenders, accent: "#00D4AA", Icon: Users },
  revenue: { img: imgGrowth, accent: "#4AC9E3", Icon: TrendingUp },
};

const SEV: Record<string, string> = { positive: "#00D4AA", neutral: "#2E9BDC", warning: "#E8A33C" };

export default function OvInsights({
  lang, summary, insights, loading, error, generated, onGenerate, updatedLabel,
}: {
  lang: "fr" | "en";
  summary: string;
  insights: OverviewInsight[];
  loading: boolean;
  error?: string | null;
  generated: boolean;
  onGenerate: () => void;
  updatedLabel?: string | null;
}) {
  const [open, setOpen] = useState<number | null>(null);
  const T = (fr: string, en: string) => (lang === "en" ? en : fr);

  return (
    <div
      className="rounded-2xl relative overflow-hidden"
      style={{
        padding: 18,
        border: "1px solid var(--pp-bg-border)",
        background:
          "radial-gradient(1200px 340px at 10% -14%, rgba(46,155,220,.24), transparent 62%), radial-gradient(900px 320px at 92% 118%, rgba(155,127,232,.22), transparent 62%), radial-gradient(700px 240px at 55% -50%, rgba(0,212,170,.12), transparent 60%), var(--pp-bg-card, var(--pp-bg-elevated))",
        boxShadow: "0 30px 70px -46px rgba(0,0,0,.95), 0 1px 0 rgba(255,255,255,.06) inset",
      }}
    >
      <span
        aria-hidden
        style={{
          position: "absolute", left: 0, right: 0, top: 0, height: 1,
          background: "linear-gradient(90deg, transparent, rgba(46,155,220,.7), rgba(155,127,232,.7), transparent)",
        }}
      />
      <div className="flex items-start justify-between gap-3 flex-wrap">
        <div className="flex items-center gap-2.5 min-w-0">
          <span
            className="rounded-xl flex items-center justify-center shrink-0 relative"
            style={{ width: 36, height: 36, background: "linear-gradient(140deg,#2E9BDC,#9B7FE8)", boxShadow: "0 10px 26px -10px #2E9BDC, 0 1px 0 rgba(255,255,255,.25) inset" }}
          >
            <Sparkles className={`w-4 h-4 text-white ${loading ? "animate-pulse" : ""}`} />
          </span>
          <div className="min-w-0">
            <h3 className="flex items-center gap-2" style={{ fontSize: 14.5, fontWeight: 800, color: "var(--pp-text-primary)", letterSpacing: "-.015em" }}>
              {T("Insights IA", "AI insights")}
              {updatedLabel && !loading && (
                <span
                  className="rounded-full px-2 py-0.5"
                  style={{ fontSize: 10, fontWeight: 700, color: "#00D4AA", background: "rgba(0,212,170,.12)", border: "1px solid rgba(0,212,170,.35)" }}
                >
                  {updatedLabel}
                </span>
              )}
            </h3>
            <p style={{ fontSize: 10.5, color: "var(--pp-text-muted)" }}>
              {T("Généré par Claude — mis à jour automatiquement chaque 24 h", "Generated by Claude — auto-refreshed every 24h")}
            </p>
          </div>
        </div>
        <button
          onClick={onGenerate}
          disabled={loading}
          className="px-3 py-1.5 rounded-lg text-[12px] flex items-center gap-1.5 text-white disabled:opacity-60 transition-transform hover:-translate-y-0.5"
          style={{ background: "linear-gradient(120deg,#2E9BDC,#9B7FE8)", boxShadow: "0 14px 30px -18px #9B7FE8" }}
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
          {loading ? T("Analyse…", "Analyzing…") : T("Régénérer", "Regenerate")}
        </button>
      </div>

      {error && <p className="mt-3" style={{ fontSize: 12, color: "#E84C4C" }}>{error}</p>}

      {loading && insights.length === 0 && (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3 mt-4">
          {Array.from({ length: 3 }).map((_, i) => (
            <div
              key={i}
              className="rounded-xl animate-pulse"
              style={{ height: 168, border: "1px solid var(--pp-bg-border)", background: "var(--pp-bg-elevated)" }}
            />
          ))}
        </div>
      )}

      {!generated && !loading && !error && (
        <p className="mt-3" style={{ fontSize: 12, color: "var(--pp-text-muted)", maxWidth: 660 }}>
          {T(
            "L'analyse se génère automatiquement dès que vos données sont chargées.",
            "The analysis is generated automatically as soon as your data is loaded.",
          )}
        </p>
      )}

      {summary && (
        <p
          className="mt-3 rounded-xl"
          style={{
            fontSize: 12.5, lineHeight: 1.6, color: "var(--pp-text-primary)", maxWidth: 940,
            padding: "10px 12px",
            background: "linear-gradient(120deg, rgba(46,155,220,.10), rgba(155,127,232,.06))",
            borderLeft: "2px solid #2E9BDC",
          }}
        >
          {summary}
        </p>
      )}


      {insights.length > 0 && (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3 mt-4">
          {insights.map((it, i) => {
            const art = ART[it.category] ?? ART.performance;
            const isOpen = open === i;
            return (
              <button
                key={`${it.title}-${i}`}
                onClick={() => setOpen(isOpen ? null : i)}
                className="text-left rounded-xl relative overflow-hidden transition-transform duration-300 hover:-translate-y-1"
                style={{
                  border: "1px solid var(--pp-bg-border)",
                  background: "var(--pp-bg-elevated)",
                  boxShadow: isOpen
                    ? `0 22px 44px -26px ${art.accent}, 0 0 0 1px ${art.accent}55 inset`
                    : "0 16px 34px -28px rgba(0,0,0,.9)",
                }}
              >
                <div className="relative" style={{ height: 82, overflow: "hidden" }}>
                  <img
                    src={art.img}
                    alt=""
                    loading="lazy"
                    width={1024}
                    height={512}
                    className="w-full h-full object-cover"
                    style={{ transform: isOpen ? "scale(1.08)" : "scale(1)", transition: "transform .4s ease", opacity: 0.9 }}
                  />
                  <span style={{ position: "absolute", inset: 0, background: "linear-gradient(180deg, transparent 10%, var(--pp-bg-elevated) 96%)" }} />
                  <span
                    className="absolute left-3 top-3 rounded-lg flex items-center justify-center"
                    style={{ width: 26, height: 26, background: `${art.accent}26`, border: `1px solid ${art.accent}66`, color: art.accent, backdropFilter: "blur(6px)" }}
                  >
                    <art.Icon className="w-3.5 h-3.5" />
                  </span>
                  {it.metric && (
                    <span
                      className="absolute right-3 top-3 rounded-full px-2 py-0.5 tabular-nums"
                      style={{
                        fontSize: 10.5, fontWeight: 800,
                        color: SEV[it.severity] ?? art.accent,
                        background: "rgba(0,0,0,.45)",
                        border: `1px solid ${(SEV[it.severity] ?? art.accent)}55`,
                        backdropFilter: "blur(6px)",
                      }}
                    >
                      {it.metric}
                    </span>
                  )}
                </div>
                <div style={{ padding: "8px 12px 12px" }}>
                  <div style={{ fontSize: 12.5, fontWeight: 800, color: "var(--pp-text-primary)" }}>{it.title}</div>
                  <p className="mt-1" style={{ fontSize: 11.5, lineHeight: 1.5, color: "var(--pp-text-muted)" }}>{it.finding}</p>
                  {it.action && (
                    <p
                      className="rounded-lg"
                      style={{
                        fontSize: 11, lineHeight: 1.45,
                        paddingLeft: 9, paddingRight: 9,
                        color: "var(--pp-text-primary)",
                        background: `${art.accent}14`, borderLeft: `2px solid ${art.accent}`,
                        maxHeight: isOpen ? 200 : 0, overflow: "hidden",
                        opacity: isOpen ? 1 : 0, transition: "all .3s ease",
                        marginTop: isOpen ? 8 : 0, paddingTop: isOpen ? 7 : 0, paddingBottom: isOpen ? 7 : 0,
                      }}
                    >
                      {it.action}
                    </p>
                  )}
                  <span className="block mt-2" style={{ fontSize: 10, color: "var(--pp-text-muted)" }}>
                    {isOpen ? T("Masquer la recommandation", "Hide recommendation") : T("Voir la recommandation", "See recommendation")}
                  </span>
                </div>
              </button>
            );
          })}
        </div>
      )}
    </div>
  );
}
