-- 1) Enforce that encrypted lemtel_config rows must be marked as secret
ALTER TABLE public.lemtel_config
  ADD CONSTRAINT lemtel_config_encrypted_requires_secret
  CHECK (encrypted IS NOT TRUE OR is_secret IS TRUE) NOT VALID;

-- 2) Restrict Realtime broadcast on planipret_profiles to non-sensitive columns
--    (excludes ns_jwt, ns_refresh_token, ns_access_token, ms365_access_token,
--     ms365_refresh_token, ms365_id_token, maestro_broker_token, sip_password)
ALTER PUBLICATION supabase_realtime SET TABLE public.planipret_profiles
  (id, user_id, organization_id, full_name, email, phone, extension, ns_domain, ns_user_id, role, mobile_app_enabled, voice_agent_enabled, avatar_url, language, metadata, created_at, updated_at, elevenlabs_agent_id, ns_jwt_expires_at, privacy_accepted_at, privacy_version, recording_consent, dnd_enabled, dnd_start_time, dnd_end_time, dnd_auto_schedule, dnd_message_fr, notif_calls, notif_sms, notif_voicemails, notif_ai, notif_reminders, onboarding_completed, onboarding_step, first_login_at, notif_hot_leads, notif_appointment_reminder, notif_missed_call, notif_morning_brief, notif_eod_summary, last_morning_brief_at, last_eod_summary_at, maestro_broker_id, maestro_token_expires_at, maestro_connected, maestro_last_sync_at, voicemail_greeting_text, voicemail_greeting_voice_id, voicemail_greeting_audio_url, voicemail_greeting_updated_at, voicemail_greeting_active, ava_sessions_count, ava_last_session_at, ava_preferred_lang, ava_autonomy_mode, elevenlabs_session_count, elevenlabs_last_session, elevenlabs_agent_status, widget_enabled, status, ms365_token_expiry, ms365_email, ms365_display_name, ns_extension, ns_sip_username, ns_linked, ns_linked_at, sip_username, sip_domain, sip_proxy, ns_sip_password_ref, ns_link_method, auth_method, login_email, onboarding_email_sent_at, ava_learned_preferences, ava_learned_updated_at, ms365_scopes, ns_sip_password_ref_mobile, ns_mobile_device_id, ns_widget_device_id, ava_voice_id, ava_voice_stability, ava_voice_similarity, ava_voice_style, ava_voice_speed, ava_chat_mode);
