// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});

const protectedEdgeFunctions = new Set(['fusionpbx-proxy', 'pbx-write', 'extension-manage']);
const originalInvoke = supabase.functions.invoke.bind(supabase.functions);

function isUnauthorizedFunctionError(error: unknown) {
  const err = error as { message?: string; context?: { status?: number } } | null;
  return err?.context?.status === 401 || /\b401\b|unauthorized/i.test(err?.message || '');
}

async function refreshSessionSafely() {
  try {
    return (await supabase.auth.refreshSession()).data.session ?? null;
  } catch {
    return null;
  }
}

/**
 * Harden protected Edge Function calls against auth hydration / stale JWT races.
 *
 * Supabase normally injects the current access token automatically, but the
 * Lemtel PBX pages poll and auto-sync immediately after route changes. In the
 * desktop/mobile webviews this can happen while auth storage is still hydrating,
 * or with an access token that is seconds from expiry. The PBX proxy correctly
 * returns 401 in that case, but the app should refresh/retry instead of letting
 * that response bubble into the global runtime overlay / blank screen.
 */
(supabase.functions as any).invoke = async (functionName: string, options?: Record<string, unknown>) => {
  const name = String(functionName);
  const invokeWithToken = async (accessToken?: string) => originalInvoke(functionName, {
    ...(options as Record<string, unknown> | undefined),
    headers: {
      ...((options as { headers?: Record<string, string> } | undefined)?.headers || {}),
      ...(accessToken ? { Authorization: `Bearer ${accessToken}` } : {}),
    },
  } as never);

  let { data: { session } } = await supabase.auth.getSession();
  const nowSec = Math.floor(Date.now() / 1000);
  if (!session || (session.expires_at && session.expires_at - nowSec < 120)) {
    session = (await refreshSessionSafely()) ?? session;
  }

  if (!session?.access_token) {
    if (protectedEdgeFunctions.has(name)) {
      console.warn(`[supabase] Skipped ${name}: no authenticated session yet`);
      return {
        data: { error: 'AUTH_REQUIRED', message: 'Please sign in again before calling the PBX service.' },
        error: null,
      } as Awaited<ReturnType<typeof supabase.functions.invoke>>;
    }
    return originalInvoke(functionName, options as never);
  }

  let result = await invokeWithToken(session.access_token);

  if (isUnauthorizedFunctionError(result.error)) {
    const refreshed = await refreshSessionSafely();
    if (refreshed?.access_token) {
      result = await invokeWithToken(refreshed.access_token);
    }
  }
  if (isUnauthorizedFunctionError(result.error) && protectedEdgeFunctions.has(name)) {
    console.warn(`[supabase] ${name} still returned 401 after token refresh`);
    return {
      data: { error: 'AUTH_REQUIRED', message: 'Please sign in again before calling the PBX service.' },
      error: null,
    } as Awaited<ReturnType<typeof supabase.functions.invoke>>;
  }
  return result;
};